### PR TITLE
Minimal security threeshold

### PR DESCRIPTION
**Pull request by adi90x**
Hello, 

As discussed, I have add a user defined threshold for the security preset to be activated
I can put an "input" instead of fixed value not sure we can have both available ? 

Regards,

### CODE REVIEW

**Comment by jmcollin78** [comment]
Hello @adi90x 

Many thanks for your PR. I will quickly have a look to this, and I came back with eventual comments.

**Review by jmcollin78 — APPROVED** [review]
Fine !

**Comment by jmcollin78** [comment]
I will integrate your code. The errors were there before and I am currently fixing it.

**Comment by adi90x** [comment]
Thanks a lot ! 
One quick point I have just seen, it seems a bit strange the way the interface react when type in the field I have added ( it seems it didn't like input that start by 0.xxx  not sure if you have seen it ?

**Comment by jmcollin78** [comment]
@adi90x 

When using your PR on existing thermostat, I've got this error:

```
Traceback (most recent call last):
  File "/workspaces/core/config/custom_components/versatile_thermostat/climate.py", line 1179, in _async_temperature_changed
    await self._async_control_heating(force=False)
  File "/workspaces/core/config/custom_components/versatile_thermostat/climate.py", line 1740, in _async_control_heating
    security: bool = await self.check_security()
  File "/workspaces/core/config/custom_components/versatile_thermostat/climate.py", line 1670, in check_security
    and self._prop_algorithm.on_percent > self._security_min_on_percent
TypeError: '>' not supported between instances of 'int' and 'NoneType'
```

We will have to intialise the _security_min_on_percent with the default value if None to be upward compatible.
I will add a quick fix.

**Comment by jmcollin78** [comment]
> One quick point I have just seen, it seems a bit strange the way the interface react when type in the field I have added ( it seems it didn't like input that start by 0.xxx not sure if you have seen it ?

Yes it seems to be a bug in the interface with '.'. 0.0 seems to be not accepted.

**Comment by adi90x** [comment]
> > One quick point I have just seen, it seems a bit strange the way the interface react when type in the field I have added ( it seems it didn't like input that start by 0.xxx not sure if you have seen it ?
> 
> Yes it seems to be a bug in the interface with '.'. 0.0 seems to be not accepted.

Quite strange but it seems to be the same with TPI coeff also so I guess we can close that :)

**Pull request merged**
