### PR TITLE
move AC mode config under the right configuration step

### PR DESCRIPTION
**Pull request by muchasuerte**

### CODE REVIEW

**Comment by jmcollin78** [comment]
Hello @muchasuerte ,

Thank you for your contribution. Could you please explains what you are trying to achieve (in the first post) ? So that it will be more easier for me to understand the changes.

I will have a look this week.

**Comment by jmcollin78** [comment]
Please add a unit test that show your changes are working as expected.

**Comment by jmcollin78** [comment]
> One point, how I can run It? Do you have a guide to run the unit test locale o in remote on GitHub?

I run all the unit tests in VSCode in container mode, directly from the sidebar:

Capture d’écran 2023-09-26 à 20 21 43

Sometimes, the test are run but the results doesn't show in the bar (a VSCode bug which is in PR now). If you ran into this bug, just open a Terminal and type:
$ cd config/custom_components/versatile_thermostat
$ pytest ./tests


All the tests will be run and all should be green.

**Comment by muchasuerte** [comment]
yes, I see it's a lot of time that I'm not develop anymore so I need the
study vscode and container (I was developing by using kdevelop or kate as
editor + chroot)

now at container init the script fail because it is trying to mount a
folder

source=/Users/jmcollin/SugarSync/Projets/home-assistant/core,target=/home/vscode/core,type=bind,consistency=cached

which of course does not exist on my end, what does it need on that folder
just the home-assistant sorce code or a virtualenv?

"source=${localWorkspaceFolder}/home-assistant/core,target=/home/vscode/core,type=bind,consistency=cached"
,
+ some instruction to set the folder *home-assistant/core*


Il giorno mar 26 set 2023 alle ore 20:24 Jean-Marc Collin <
***@***.***> ha scritto:

**Comment by jmcollin78** [comment]
> source=/Users/jmcollin/SugarSync/Projets/home-assistant/core,target=/home/vscode/core,type=bind,consistency=cached

This is to import all the HA core code. It is then easier to debug or develop with all the HA core code.

You can safely comment out this line.

If it is too much complicate to implement a unit test I can do it myself on mext week. Please just resolve the code points and I will merge + implements unit test on next week.

**Comment by muchasuerte** [comment]
I did a try on setup the environment but I'm blocked on this error

ImportError: Error importing plugin
"pytest_homeassistant_custom_component": No module named
'pytest_homeassistant_custom_component'

I did some progress via this script

git clone --branch "2023.9.2" --single-branch --depth 1
https://github.com/home-assistant/core.git /home/vscode/core/homeassistant
cp -a /home/vscode/core/homeassistant/tests
/home/vscode/core/pytest_homeassistant_custom_component
pip install homeassistant==2023.9.2
pip install pytest
sudo chown -R vscode: /home/vscode/core

but again I'm retrieving strange error from pytest

Moreover, it seems that pytest need ***@***.***" before any test
function , it is a mess at least for me...

for now I give up! I'll try next week


Il giorno dom 1 ott 2023 alle ore 09:04 Jean-Marc Collin <
***@***.***> ha scritto:

**Comment by jmcollin78** [comment]
You have to do:

$ pip install -r requirements_dev.txt
$ pip install -r requirements_test.txt

This will install the pytest_homeassistant_custom_component

**Comment by muchasuerte** [comment]
Thank you for your help, now I was able to run all tests :

command: pytest --asyncio-mode=auto --log-cli-level=ERROR
custom_components/versatile_thermostat/tests/

current result:

Results (12.57s):
      35 passed
       5 failed
         -
custom_components/versatile_thermostat/tests/test_config_flow.py:30
test_user_config_flow_over_switch[True-True]
         -
custom_components/versatile_thermostat/tests/test_config_flow.py:129
test_user_config_flow_over_climate[True-True]
         -
custom_components/versatile_thermostat/tests/test_config_flow.py:216
test_user_config_flow_window_auto_ok[True-True]
         -
custom_components/versatile_thermostat/tests/test_config_flow.py:385
test_user_config_flow_over_4_switches[True-True]
         - custom_components/versatile_thermostat/tests/test_tpi.py:6
test_tpi_calculation[True-True]

I'll fix it in the upcoming days!



Il giorno mar 3 ott 2023 alle ore 07:58 Jean-Marc Collin <
***@***.***> ha scritto:

**Comment by muchasuerte** [comment]
All tests executed without errors


$ pytest --asyncio-mode=auto --log-cli-level=ERROR custom_components/versatile_thermostat/tests
Test session starts (platform: linux, Python 3.11.4, pytest 7.3.1, pytest-sugar 0.9.7)
rootdir: /workspaces/versatile_thermostat
plugins: respx-0.20.2, syrupy-4.2.1, homeassistant-custom-component-0.13.54, cov-4.1.0, anyio-4.0.0, test-groups-1.0.3, requests-mock-1.11.0, picked-0.4.6, aiohttp-1.0.4, unordered-0.5.2, asyncio-0.21.0, sugar-0.9.7, pytest_freezer-0.4.8, xdist-3.3.1, socket-0.6.0, timeout-2.1.0
asyncio: mode=Mode.AUTO
collected 40 items                                                                                                                   

 custom_components/versatile_thermostat/tests/test_binary_sensors.py::test_security_binary_sensors[True-True] ✓          2% ▍         
 custom_components/versatile_thermostat/tests/test_binary_sensors.py::test_overpowering_binary_sensors[True-True] ✓      5% ▌         
 custom_components/versatile_thermostat/tests/test_binary_sensors.py::test_window_binary_sensors[True-True] ✓            8% ▊         

--------------------------------------------------------- live log teardown ----------------------------------------------------------
ERROR    custom_components.versatile_thermostat.underlyings:underlyings.py:124 Unable to find service homeassistant.turn_on
 custom_components/versatile_thermostat/tests/test_binary_sensors.py::test_motion_binary_sensors[True-True] ✓           10% █         
 custom_components/versatile_thermostat/tests/test_binary_sensors.py::test_presence_binary_sensors[True-True] ✓         12% █▍        
 custom_components/versatile_thermostat/tests/test_binary_sensors.py::test_binary_sensors_over_climate_minimal[True-True] ✓15% █▌        
----------------------------------------------------------- live log call ------------------------------------------------------------
ERROR    custom_components.versatile_thermostat.underlyings:underlyings.py:416 VersatileThermostat-TheOverClimateMockName-climate.mock_climate - Cannot find the underlying climate entity: climate.mock_climate. Thermostat will not be operational
ERROR    custom_components.versatile_thermostat.underlyings:underlyings.py:416 VersatileThermostat-TheOverClimateMockName-climate.mock_climate - Cannot find the underlying climate entity: climate.mock_climate. Thermostat will not be operational

 custom_components/versatile_thermostat/tests/test_bugs.py::test_bug_56[True-True] ✓                                    18% █▊        
 custom_components/versatile_thermostat/tests/test_bugs.py::test_bug_63[True-True] ✓                                    20% ██        
 custom_components/versatile_thermostat/tests/test_bugs.py::test_bug_64[True-True] ✓                                    22% ██▍       
 custom_components/versatile_thermostat/tests/test_bugs.py::test_bug_66[True-True] ✓                                    25% ██▌       
 custom_components/versatile_thermostat/tests/test_config_flow.py::test_show_form[True-True] ✓                          28% ██▊       
 custom_components/versatile_thermostat/tests/test_config_flow.py::test_user_config_flow_over_switch[True-True] ✓       30% ███       
----------------------------------------------------------- live log call ------------------------------------------------------------
ERROR    custom_components.versatile_thermostat.underlyings:underlyings.py:416 VersatileThermostat-TheOverClimateMockName-climate.mock_climate - Cannot find the underlying climate entity: climate.mock_climate. Thermostat will not be operational

 custom_components/versatile_thermostat/tests/test_config_flow.py::test_user_config_flow_over_climate[True-True] ✓      32% ███▍      
 custom_components/versatile_thermostat/tests/test_config_flow.py::test_user_config_flow_window_auto_ok[True-True] ✓    35% ███▌      
----------------------------------------------------------- live log call ------------------------------------------------------------
ERROR    custom_components.versatile_thermostat.config_flow:config_flow.py:399 Only one window detection method should be used. Use window_sensor or auto window open detection but not both

 custom_components/versatile_thermostat/tests/test_config_flow.py::test_user_config_flow_window_auto_ko[True-True] ✓    38% ███▊      
 custom_components/versatile_thermostat/tests/test_config_flow.py::test_user_config_flow_over_4_switches[True-True] ✓   40% ████      
 custom_components/versatile_thermostat/tests/test_movement.py::test_movement_management_time_not_enough[True-True] ✓   42% ████▍     
 custom_components/versatile_thermostat/tests/test_movement.py::test_movement_management_time_enough_and_presence[True-True] ✓45% ████▌     
 custom_components/versatile_thermostat/tests/test_movement.py::test_movement_management_time_enoughand_not_presence[True-True] ✓48% ████▊     
 custom_components/versatile_thermostat/tests/test_multiple_switch.py::test_one_switch_cycle[True-True] ✓               50% █████     
 custom_components/versatile_thermostat/tests/test_multiple_switch.py::test_multiple_switchs[True-True] ✓               52% █████▍    
 custom_components/versatile_thermostat/tests/test_open_window_algo.py::test_open_window_algo ✓                         55% █████▌    
 custom_components/versatile_thermostat/tests/test_open_window_algo.py::test_open_window_algo_wrong ✓                   57% █████▊    
 custom_components/versatile_thermostat/tests/test_power.py::test_power_management_hvac_off[True-True] ✓                60% ██████    
 custom_components/versatile_thermostat/tests/test_power.py::test_power_management_hvac_on[True-True] ✓                 62% ██████▍   
 custom_components/versatile_thermostat/tests/test_power.py::test_power_management_energy_over_switch[True-True] ✓      65% ██████▌   
 custom_components/versatile_thermostat/tests/test_power.py::test_power_management_energy_over_climate[True-True] ✓     68% ██████▊   
 custom_components/versatile_thermostat/tests/test_security.py::test_security_feature[True-True] ✓                      70% ███████   
 custom_components/versatile_thermostat/tests/test_sensors.py::test_sensors_over_switch[True-True] ✓                    72% ███████▍  
 custom_components/versatile_thermostat/tests/test_sensors.py::test_sensors_over_climate[True-True] ✓                   75% ███████▌  
 custom_components/versatile_thermostat/tests/test_sensors.py::test_sensors_over_climate_minimal[True-True] ✓           78% ███████▊  
 custom_components/versatile_thermostat/tests/test_start.py::test_over_switch_full_start[True-True] ✓                   80% ████████  
 custom_components/versatile_thermostat/tests/test_start.py::test_over_climate_full_start[True-True] ✓                  82% ████████▍ 
 custom_components/versatile_thermostat/tests/test_start.py::test_over_4switch_full_start[True-True] ✓                  85% ████████▌ 
 custom_components/versatile_thermostat/tests/test_tpi.py::test_tpi_calculation[True-True] ✓                            88% ████████▊ 
 custom_components/versatile_thermostat/tests/test_window.py::test_window_management_time_not_enough[True-True] ✓       90% █████████ 
 custom_components/versatile_thermostat/tests/test_window.py::test_window_management_time_enough[True-True] ✓           92% █████████▍
 custom_components/versatile_thermostat/tests/test_window.py::test_window_auto_fast[True-True] ✓                        95% █████████▌
 custom_components/versatile_thermostat/tests/test_window.py::test_window_auto_auto_stop[True-True] ✓                   98% █████████▊
 custom_components/versatile_thermostat/tests/test_window.py::test_window_auto_no_on_percent[True-True] ✓              100% ██████████

Results (12.45s):
      40 passed

**Comment by jmcollin78** [comment]
Fine ! Great work. There was 2 or 3 others remarks you don't fix (backward compatibility). Fix them and I will be able to merge this week-end.

**Comment by muchasuerte** [comment]
hello Jean Marc,

can you tell me more, what is missing so I'll fix?

Il giorno ven 13 ott 2023 alle ore 15:50 Jean-Marc Collin <
***@***.***> ha scritto:

**Comment by jmcollin78** [comment]
See above:
Capture d’écran 2023-10-14 à 18 51 14

**Comment by jmcollin78** [comment]
Hello @muchasuerte ,

Do you think it will be possible to finish this MR ? I will have big changes to do, and then you will have a big merge/rebase to do after my changes.

You already have conflicts because next week i have implement many enhancements and fixes.

**Comment by muchasuerte** [comment]
Give me 24h, I'll try to finalize the change by today.

Il Ven 20 Ott 2023, 08:10 Jean-Marc Collin ***@***.***> ha
scritto:

**Comment by muchasuerte** [comment]
I did a review and to me there is no need to have backward compatibility
because the PropAlgorithm.calculate(...) is invoked only by

when I did the pull I got some error
custom_components/versatile_thermostat/tests/test_config_flow.py:129

E       AssertionError: assert {'ac_mode': F...p': 17.0, ...} ==
{'boost_temp'..._min': 5, ...}
E         Omitting 20 identical items, use -vv to show
E         Left contains 1 more item:
E         {'ac_mode': False}
E         Full diff:
E           {
E         +  'ac_mode': False,
E         -  'boost_temp': 18,...
E
E         ...Full output truncated (32 lines hidden), use '-vv' to show

I have to resolve it


Il giorno ven 20 ott 2023 alle ore 09:30 Andrea Nicotra <
***@***.***> ha scritto:

**Comment by jmcollin78** [comment]
Nice job !
Their is still some conflict to resolve.

**Comment by muchasuerte** [comment]
I'm doing the rebase of my changes on top you main repo, it seems easy to
reinstate.

I'll try by today

Il Ven 20 Ott 2023, 11:35 Jean-Marc Collin ***@***.***> ha
scritto:

**Comment by muchasuerte** [comment]
hello I did the rebase of my changes on top of your code

test is 99% ok, I cannot understand what go wrong with this

FAILED custom_components/versatile_thermostat/tests/test_multiple_switch.py::test_multiple_climates_underlying_changes[True-True] - AssertionError: assert 0 == 4
custom_components/versatile_thermostat/tests/test_multiple_switch.py:446 test_multiple_climates_underlying_changes[True-True]

I have no idea how to resolve it

**Comment by jmcollin78** [comment]
I will merge and have a look at it. Thanks for your work @muchasuerte !

**Comment by jmcollin78** [comment]
FYI, you have lost all changes I made into climate.py at
```
@callback
    async def _async_climate_changed(self, event):
```

That is why the test was failed.

**Comment by muchasuerte** [comment]
I'm sorry for that.

Does it make any sense that you revert my pull request? I can try on run
the rebase again on my end.


Il Sab 21 Ott 2023, 12:29 Jean-Marc Collin ***@***.***> ha
scritto:

**Comment by jmcollin78** [comment]
No I have made the fx. Do not worry I fix it rapidly.

I have published a pre-release with your PR: https://github.com/jmcollin78/versatile_thermostat/releases/tag/3.6.0.beta3

Can you please make some tests in your environment with it so that I will be sure all is correctly reported.
This can be done with HACS, you have to check the "See pre-release".
If is ok, I will publish a final release.

**Comment by muchasuerte** [comment]
I'll do, just before I have to update HA from 2023.9.2 to 2023.10.3

Il giorno sab 21 ott 2023 alle ore 15:31 Jean-Marc Collin <
***@***.***> ha scritto:

**Comment by jmcollin78** [comment]
I have added some unit tests for over switch ac mode and fixed many problems (not your fault).
So take the last one which fixes the problems: https://github.com/jmcollin78/versatile_thermostat/releases/tag/3.6.0.beta4

**Pull request merged**
