### PR TITLE
Updated en.json translations

### PR DESCRIPTION
**Pull request by EPicLURcher**
reviewed and made minor changes to en.json translations

### CODE REVIEW

**Review by jmcollin78 — CHANGES_REQUESTED** [review]
Than you for this, but you have to copy this into the strings.json also (at root directory)

**Comment by jmcollin78** [comment]
Hello @EPicLURcher , thank you for this update.
Since last week-end I have pusblished a new major release with many new translation. Do you think it is possible to take this into account ?

**Comment by EPicLURcher** [comment]
Hey, 

Yes, sorry, I know my last PR wasn't accepted because I needed to do another file as well. Sorry about that, had some stuff to fix at home. I'll get these translations done by tomorrow for you! 

Thank you

**Comment by EPicLURcher** [comment]
@jmcollin78  just to double check - I copy all the lines in the en.json into strings.json (replacing all the contents in strings?)

**Pull request closed without merging**
