### PR TITLE
Update sk.json

### PR DESCRIPTION
**Pull request by misa1515**

### CODE REVIEW

**Comment by jmcollin78** [comment]
Thank you @misa1515 ,

You have a syntax error in the sk.json:

`Error: R] [JSON] Invalid JSON file translations/sk.json`

**Comment by misa1515** [comment]
@jmcollin78 thankyou, now corrected.

**Review by jmcollin78 — APPROVED** [review]
Thank you @misa1515 !

**Comment by jmcollin78** [comment]
For the future, may I contact you If i have some major change in the localisation of VTherm ?

**Comment by misa1515** [comment]
@jmcollin78, for sure, you can contact me.

**Pull request merged**
