### PR TITLE
issue with ac and mouvement detection

### PR DESCRIPTION
**Pull request by cddu33**
https://github.com/jmcollin78/versatile_thermostat/issues/470

issue with ac and mouvement detection

### CODE REVIEW

**Review by jmcollin78 — COMMENTED** [review]
Thank you for this fix. There is already a method named find_preset_temp which calculate the preset_name depending on the AC mode (and other stuff).

Can we use it in that case ?

**Comment by cddu33** [comment]
No because motion presept not use it.

**Comment by cddu33** [comment]
i modify function find_preset_temps for use with activity preset
j'ai modifier la fonction find_preset_temps pour être utilisable avec le module Activité (détection de mouvement)

**Review by jmcollin78 — APPROVED** [review]
Thank you ! Will check if unit tests are ok. Not totally sure it will pass as is.

**Comment by jmcollin78** [comment]
All is fine. I will release soon.

**Comment by jmcollin78** [comment]
https://github.com/jmcollin78/versatile_thermostat/releases/tag/6.2.5

**Pull request merged**
