### PR TITLE
switch from HEAT to COOL mode

### PR DESCRIPTION
**Pull request by muchasuerte**
Hello Collin, 

I need the capability to switch from HEAT to COOL mode, does it make sense for you?

I have an aermec unit which can generate both cooling and heating, it is managed by ZBMINI-L2 ZigBee, if the thermostat is configured in AC mode I would like support both.

unit test updated as well!

### CODE REVIEW

**Comment by jmcollin78** [comment]
Please rebase and I would be glad to merge !

**Comment by jmcollin78** [comment]
I think it is more complicated than this. In the code, it is checked if the VTherm is in ac_mode instead of checking is the VTherm is in HVACMode COOL. See example in base_thermostat.py line 268.

So you will have to change all this code and see if all unit tests are running. I guess not.

**Comment by muchasuerte** [comment]
I did the chance on top of your last chance today the rebase should not be
needed, I guess.

On the first pull request it was working fine all unit tests are passed
without errors

Il Lun 30 Ott 2023, 15:15 Jean-Marc Collin ***@***.***> ha
scritto:

**Comment by jmcollin78** [comment]
I finish an important development about regulation and I come back with your PR.

**Comment by jmcollin78** [comment]
I wonder why I see all my commits into you PR. Did you have some troubles with the rebase ?

**Comment by muchasuerte** [comment]
I did the rebase but maybe I did something of wrong

Let me try to resolve the issue on my end by tomorrow.

Il giorno mer 1 nov 2023 alle ore 21:18 Jean-Marc Collin <
***@***.***> ha scritto:

**Comment by jmcollin78** [comment]
What i suggest is to restart from scratch. Checkout the main branch and
redo your work

Le mer. 1 nov. 2023, 21:21, Andrea Nicotra ***@***.***> a
écrit :

**Comment by muchasuerte** [comment]
yes, it is what I did "reset from your main then cherry-pick from my local
branch", I did the squash of 2 changes hoping it is not a problem.

**Comment by jmcollin78** [comment]
Merged ! Thank you. It will be in the next release.

**Pull request merged**
