### PR TITLE
Create sk.json

### PR DESCRIPTION
**Pull request by misa1515**

### CODE REVIEW

**Comment by jmcollin78** [comment]
Thank you @misa1515  for your contribution. I will publish a new release with new key to translate. So I keep the PR open until I publish the new keys.

**Review by misa1515 — COMMENTED** [review]
updated

**Comment by jmcollin78** [comment]
Sorry but there is more keys missing. I add all thoses keys in the strings.json:

```
         "valve_entity_id": "1rst valve number",
          "valve_entity2_id": "2nd valve number",
          "valve_entity3_id": "3rd valve number",
          "valve_entity4_id": "4th valve number"
```

You should find it 4 times: in type/data, type/data_description and same in options section.

**Comment by misa1515** [comment]
no problem.
Last time was only 1 more code line (when I checked it).
Now are more new lines.
Updated.

**Comment by jmcollin78** [comment]
I will merge. But because I'm still developping some features, may I ask you some translations ? I will integrate them.

"auto_regulation_strong": "Strong",
"auto_regulation_medium": "Medium",
"auto_regulation_light": "Light",
"auto_regulation_none": "No auto-regulation"
"auto_regulation_mode": "Self-regulation"
"auto_regulation_mode": "Auto adjustment of the target temperature"

Thank you in advance !

**Pull request merged**
