### PR TITLE
Revised _percent_open and closing_degree logic

### PR DESCRIPTION
**Pull request by gibsonshine**
### Description

This PR proposes a revised `_percent_open` and `closing_degree` logic to resolve an issue in the Sonoff TRVZB where the `hvac_action` repeatedly reverts to an _Idle_ state. This occurs when `_percent_open + closing_degree = 100`, preventing the TRV from maintaining a _Heating_ state, regardless of whether it should be heating.

### Linked Issues

This PR relates to the discussion on Feature Request #645 .

### Proposed Changes

- Adjusted the `_percent_open` calculation to ensure it respects the TRVZB's operational thresholds without defaulting to _Idle_ unnecessarily.
- Refactored the logic surrounding `closing_degree` to better align with the TRV's state transitions, ensuring accurate `hvac_action` reporting.
- Introduced additional safeguards to prevent edge cases where `_percent_open` and `closing_degree` cause conflicts, especially when nearing their combined maximum value.

### Testing

**Scenario 1:**  
Tested with a Sonoff TRVZB at various `closing_degree` values, confirming that `hvac_action` transitions to _Heating_ as expected when heat is demanded.

**Scenario 2:**  
Validated that the TRV maintains _Heating_ or _Idle_ states appropriately when adjusting setpoints and during normal operation.

**Scenario 3:**  
Tested the behaviour of the `Nb device active for boiler` to ensure that it correctly counts TRVs with state = _Heating_ , and returns to zero when appropriate.

### Results

- Resolved the _Idle_ state bug. The TRV correctly transitions to _Heating_ when required and remains _Idle_ when there is no demand for heat.
- Prevented unintended resets to _Idle_ during edge cases caused by `_percent_open + closing_degree = 100`.
- The `Nb device active for boiler` behaves as anticipated, returning to zero when appropriate.

### Additional Notes

- Feedback on further edge cases to test is welcome.
- I have followed the repository's contribution guidelines, including linting the code with `black`.

Let me know if there are additional changes or tests you'd like me to include.  Thank you for considering this Pull Request!

### CODE REVIEW

**Comment by gibsonshine** [comment]
Hi @jmcollin78,

Apologies for the number of commits; I am relatively new to GitHub and had some challenges with version and branch control.

To clarify, the primary change I am proposing is in the `underlyings.py` file, specifically a revised `_percent_open` and `closing_degree` logic. These changes aim to address the issue where the Sonoff TRVZB defaults to an _Idle_ state when `_percent_open + closing_degree = 100`.

I based my modifications on **beta8**, so some of the other files in the PR may have reverted back to earlier versions unintentionally to avoid conflicts. I’ve realised that this includes changes you made in subsequent releases, particularly regarding the recalibration of the calibration temperature, which I did not intend to overwrite.

If you're interested in the logic I’ve proposed, I’d be happy for you to cherry-pick the relevant changes. Alternatively, I can rebase my changes on a newer version and submit a cleaner PR that retains your recent updates.

Thank you for your work on this project and for taking the time to review my PR. Please let me know how I can assist further.

**Comment by jmcollin78** [comment]
Hello @gibsonshine,

Thank you for this. I will try to have a look quickly.

**Comment by jmcollin78** [comment]
Can you rebase your code with the beta11 please. I have many unwanted code impact which make the review not easy. Thanks

**Comment by gibsonshine** [comment]
Hi @jmcollin78 

I have now rebased the code with your beta11 list.  This should hopefully make the proposed changes clearer.

Thank you for considering this proposal.

Kind regards

**Comment by gibsonshine** [comment]
Hi @jmcollin78 

Thank you for reviewing my code.  I understand what you mean about the 0, 99, 100, however just to reassure you that the main piece of the code I am proposing does _exactly_ what you suggest ( i.e. closing = max - open - 1 ).  Specifically this part of the code:

```
       buffer = 1  # Define a buffer to prevent idle states at boundaries
        min_closing_threshold = (
            1  # Minimum allowed value for closing_degree when system must stay active
        )
        
        if self.have_closing_degree_entity:
            # Calculate closing_degree with buffer logic
            closing_degree = self._max_opening_degree - self._percent_open - buffer
```

An example of how this looks in the software is:

image

or 

image
  
I then added in extra functions because during testing I found that the original simple function above did not account for all cases.

The first of these:

```
    if self._percent_open == 100:
        # Fully open: Adjust closing_degree to prevent idle state
        closing_degree = min_closing_threshold
```

Was because `closing_degree = self._max_opening_degree - _percent_open - buffer` might compute to a negative or zero value.

e.g. if `_percent_open = 100`, then `closing_degree = self._max_opening_degree - _percent_open - buffer = 100 - 99 - 1 = 0`

And if `_percent_open = 100` and `closing_degree = 0`, then `_percent_open + closing_degree = 100`  << This is the value where the Sonoff TRVZB reverts to Idle state.

The following function:

```
        # General case: Apply standard buffer and clamp to valid range
        closing_degree = max(
            min(self._max_opening_degree, closing_degree), min_closing_threshold
```

Ensures that `closing_degree` is at least `min_closing_threshold` (e.g. 1).  **Except** if `_percent_open = 99`, in which case `min_closing_degree = 0` (because 99 + 1 = 100 which again caused the TRV to Idle).  This is covered by the following function:

```
    elif self._percent_open == 99 and buffer == 1:
        # Almost fully open: Allow closing_degree to reach 0
        closing_degree = 0
```
        

I hope that my explanation is clear?  I also added in logging for testing these various functions, which has increased the number of lines of code, but you may not wish to keep those.

If you are able to test it locally (with the minimum regulation time set to zero to see instant changes), you will hopefully see that it works as intended.  And I can confirm from testing with my Sonoff devices that this has stopped them going into Idle when not desired.

Please let me know if you require any further information or any proposed code changes.  Thank you again for your time.

Kind regards

**Pull request closed without merging**
